# Generated by Django 4.2.4 on 2023-08-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_description_listing_sold_listing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('RCS', 'Records'), ('CTG', 'Clothing'), ('PTS', 'Posters'), ('MCS', 'Miscellaneous')], max_length=10),
        ),
    ]
