# Generated by Django 4.2.4 on 2023-08-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='like_new',
        ),
    ]
